version: '3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: ${DOCKER_USERNAME}/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      db:
        condition: service_healthy
    command: gunicorn --bind 0.0.0.0:8000 foodgram.wsgi
    restart: unless-stopped

  frontend:
    image: ${DOCKER_USERNAME}/foodgram_frontend:latest
    volumes:
      - static:/static
    restart: no

  gateway:
    image: nginx:latest
    volumes:
      - static:/static
      - media:/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped