version: '3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ../backend
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate --noinput &&
             gunicorn --bind 0.0.0.0:8000 foodgram.wsgi"

  frontend:
    build: ../frontend
    volumes:
      - static:/static
    restart: on-failure

  gateway:
    image: nginx:latest
    volumes:
      - static:/static
      - media:/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      - backend