# Generated by Django 5.2.4 on 2025-08-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_in_carts_recipe_in_favorites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
