name: Foodgram Deploy

on:
  push:
    branches:
      - main

jobs:
  lint_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install flake8
        run: pip install flake8==6.0.0

      - name: Run flake8
        run: flake8 backend/

  build_and_push_to_docker_hub:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: lint_backend
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:latest
          no-cache: true
      
      - name: Build and push nginx image
        uses: docker/build-push-action@v4
        with:
          context: infra/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_gateway:latest
          file: infra/Dockerfile.nginx

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Clean remote infra directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            rm -rf /home/yc-user/foodgram/infra/*
            mkdir -p /home/yc-user/foodgram/infra

      - name: Copy infra files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "infra/docker-compose.prod.yml"
          target: "/home/yc-user/foodgram/infra"
          strip_components: 1
          overwrite: true

      - name: Deploy containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/yc-user/foodgram/infra
            ls -la
            sudo docker-compose -f docker-compose.prod.yml down || true
            sudo docker-compose -f docker-compose.prod.yml pull
            sudo docker-compose -f docker-compose.prod.yml up -d
            sleep 20
            sudo docker-compose -f docker-compose.prod.yml exec backend python manage.py migrate --noinput
            sudo docker-compose -f docker-compose.prod.yml exec backend python manage.py collectstatic --noinput

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Foodgram успешно обновлён!
            Сервер: https://projectfoodgram.ddns.net
            Коммит: ${{ github.event.head_commit.message }}
            Автор: ${{ github.actor }}
            Ссылка: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
